### PR TITLE
Updated the Readme.md

### PR DESCRIPTION
**Pull request by rhampt**
Fixed the scan command to respond to http0.9
Change-type: patch

### CODE REVIEW

**Comment by rhampt** [comment]
Updated the Readme.md 
Fixed the scan command to respond to http0.9
Change-type: patch

**Comment by rhampt** [comment]
@resin-jenkins retest this please

**Comment by rhampt** [comment]
@

**Comment by rhampt** [comment]
@balena-ci I self-certify!

**Review by ghost — APPROVED** [review]

**Pull request merged**
