### PR TITLE
patch: Fix synchronize spelling

### PR DESCRIPTION
**Pull request by zoobot**
Signed-off-by: zoobot <rommims@gmail.com>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
You can actually go ahead and merge these on your own @zoobot No review needed from my end in the future.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by jakogut** [comment]
@zoobot In this case, it's simply a difference between American and British English. Neither is more or less correct, but one is used in the code, and the other is not. It looks like this is also log output from chrony, not a Balena product.

Matching the log output of existing software is helpful, even when spelling or grammar is incorrect. Users can grep related code for that specific error to find the nature of it. I also recommend submitting a patch upstream in cases where spelling fixes are helpful.

**Comment by vipulgupta2048** [comment]
Maybe a solution to this is putting out an exception for the word "synchronize" or whatever variant that Chrony uses in our american english checker. This eliminates the problem of fixing the language of a product/package we can't control.

**Pull request merged**
